# ── Modern CLI Replacements ───────────────────────────────────
alias ls='eza --icons --group-directories-first'
alias ll='eza -la --icons --group-directories-first --git'
alias la='eza -a --icons --group-directories-first'
alias lt='eza --tree --icons --level=2'
alias llt='eza --tree --icons --level=3 -la'
alias cat='bat --paging=never'
alias catp='bat'
alias grep='rg'
alias diff='delta'
alias top='htop'

# ── Kubernetes — get ──────────────────────────────────────────
alias k='kubectl'
alias kgp='kubectl get pods'
alias kgpa='kubectl get pods -A'
alias kgs='kubectl get svc'
alias kgd='kubectl get deploy'
alias kgi='kubectl get ingress'
alias kgn='kubectl get nodes'
alias kgns='kubectl get namespaces'
alias kgcm='kubectl get configmaps'
alias kgsec='kubectl get secrets'
alias kgpv='kubectl get pv'
alias kgpvc='kubectl get pvc'
alias kga='kubectl get all'
alias kgaa='kubectl get all -A'

# ── Kubernetes — describe / logs / exec ───────────────────────
alias kdp='kubectl describe pod'
alias kds='kubectl describe svc'
alias kdd='kubectl describe deploy'
alias kdn='kubectl describe node'
alias klf='kubectl logs -f'
alias klt='kubectl logs --tail=100'
alias kex='kubectl exec -it'
alias ktp='kubectl top pods'
alias ktn='kubectl top nodes'

# ── Kubernetes — apply / rollout / watch ─────────────────────
alias kaf='kubectl apply -f'
alias kdf='kubectl delete -f'
alias kpf='kubectl port-forward'
alias kroll='kubectl rollout'
alias krs='kubectl rollout status'
alias krr='kubectl rollout restart'
alias kwatch='watch -n2 kubectl get pods,svc,deploy,ingress'
alias kwatchall='watch -n2 kubectl get all'

# ── k9s ───────────────────────────────────────────────────────
alias k9='k9s'
alias k9a='k9s --all-namespaces'
alias k9n='k9s -n'
alias k9c='k9s --context'
alias k9ro='k9s --readonly'

# ── Helm ──────────────────────────────────────────────────────
alias h='helm'
alias hls='helm list'
alias hlsa='helm list -A'
alias hst='helm status'
alias hup='helm upgrade'
alias hin='helm install'
alias hun='helm uninstall'
alias hvals='helm get values'
alias hlint='helm lint'
alias htemp='helm template'
alias hdiff='helm diff upgrade'   # needs: helm plugin install https://github.com/databus23/helm-diff

# ── Terraform ─────────────────────────────────────────────────
alias tf='terraform'
alias tfi='terraform init'
alias tfp='terraform plan'
alias tfa='terraform apply'
alias tfd='terraform destroy'
alias tfo='terraform output'
alias tfs='terraform state'
alias tfsl='terraform state list'
alias tfss='terraform state show'
alias tfv='terraform validate'
alias tff='terraform fmt -recursive'
alias tfw='terraform workspace'
alias tfwl='terraform workspace list'
alias tfws='terraform workspace select'

# ── Cloud — AWS ───────────────────────────────────────────────
alias aws-whoami='aws sts get-caller-identity'
alias aws-regions='aws ec2 describe-regions --output table'

# ── Granted ───────────────────────────────────────────────────
alias asc='assume --console'
alias asl='granted profiles'
alias asu='assume --unset'
alias asr='assume --region'

# ── Git ───────────────────────────────────────────────────────
alias g='git'
alias gs='git status'
alias gd='git diff'
alias gds='git diff --staged'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gpl='git pull'
alias gl='git log --oneline -20'
alias glg='git log --graph --oneline --all'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gb='git branch'
alias gba='git branch -a'
alias gst='git stash'
alias gstp='git stash pop'
alias gf='git fetch --all --prune'
alias gm='git merge'
alias grb='git rebase'
alias lg='lazygit'

# ── Docker ────────────────────────────────────────────────────
alias d='docker'
alias dc='docker compose'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias dimg='docker images'
alias dlog='docker logs -f'
alias dex='docker exec -it'
alias dprune='docker system prune -af'

# ── Brew ──────────────────────────────────────────────────────
alias brewup='HOMEBREW_NO_ENV_HINTS=1 brew update && brew upgrade && brew cleanup'
alias brewout='brew outdated'

# ── Misc ──────────────────────────────────────────────────────
alias reload='exec fish'
alias path='string join \n $PATH'
alias myip='curl -s ifconfig.me'
alias localip='ipconfig getifaddr en0'
alias ports='lsof -i -P -n | grep LISTEN'
alias flushdns='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
alias weather='curl -s "wttr.in/?format=3"'
alias epoch='date +%s'
alias uuid='uuidgen | tr "[:upper:]" "[:lower:]"'
